---
sidebar: sidebar 
permalink: concepts/intro.html 
keywords: how astra control works, what is astra, kubernetes cluster, cloud volumes ontap, what is astra control 
summary: Astra es un servicio de gestión del ciclo de vida de los datos de las aplicaciones de Kubernetes que simplifica las operaciones para aplicaciones con estado. Proteja, realice backups y migre cargas de trabajo de Kubernetes con facilidad, y cree instantáneamente clones de aplicaciones que funcionen. 
---
= Más información sobre Astra Control
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


Astra Control es una solución de gestión del ciclo de vida de los datos de las aplicaciones de Kubernetes que simplifica las operaciones para aplicaciones con estado. Proteja, cree backups, replique y migre cargas de trabajo de Kubernetes con facilidad y cree instantáneamente clones de aplicaciones en funcionamiento.



== Funciones

Astra Control ofrece funcionalidades cruciales para la gestión del ciclo de vida de los datos de las aplicaciones Kubernetes:

* Gestione automáticamente el almacenamiento persistente
* Crear copias Snapshot y backups bajo demanda que se tienen en cuenta las aplicaciones
* Automatice las operaciones de backup y Snapshot condicionadas por políticas
* Replique una aplicación en un sistema remoto mediante la tecnología SnapMirror de NetApp
* Migre aplicaciones y datos de un clúster de Kubernetes a otro
* Clonar fácilmente una aplicación desde la producción hasta la configuración provisional
* Visualizar el estado de la protección y el estado de la aplicación
* Utilice una interfaz de usuario o una API para implementar los flujos de trabajo de backup y migración




== Modelos de puesta en marcha

Astra Control está disponible en dos modelos de implementación:

* *Astra Control Service*: Un servicio gestionado por NetApp que proporciona gestión de datos para aplicaciones de clústeres de Kubernetes en Google Kubernetes Engine (GKE) y Azure Kubernetes Service (AKS).
* *Astra Control Center*: Software autogestionado que proporciona gestión de datos para aplicaciones de clústeres de Kubernetes que se ejecutan en su entorno local.


[cols="1h,2d,2a"]
|===
|  | Servicio de control Astra | Astra Control Center 


| ¿Cómo se ofrece? | Como un servicio cloud totalmente gestionado de NetApp  a| 
Como software que se descarga, se instala y se gestiona



| ¿Dónde está alojado? | En un cloud público que elija NetApp  a| 
En el clúster de Kubernetes que se suministra



| ¿Cómo se actualiza? | Gestionado por NetApp  a| 
Usted administra cualquier actualización



| ¿Cuáles son las funcionalidades de gestión de datos de aplicaciones? | Mismas funcionalidades en ambas plataformas, con excepciones en los back-end de almacenamiento o a servicios externos  a| 
Mismas funcionalidades en ambas plataformas, con excepciones en los back-end de almacenamiento o a servicios externos



| ¿Cuál es el soporte del back-end de almacenamiento? | Ofertas de servicios cloud de NetApp  a| 
* Sistemas ONTAP AFF y FAS de NetApp
* Astra Data Store como back-end de almacenamiento
* Entorno de administración del almacenamiento de Cloud Volumes ONTAP


|===


== Funcionamiento del servicio Astra Control

Astra Control Service es un servicio cloud gestionado por NetApp que siempre está activo y actualizado con las últimas funcionalidades. Utiliza varios componentes para habilitar la gestión del ciclo de vida de los datos de aplicaciones.

En un nivel superior, Astra Control Service funciona de esta manera:

* Para comenzar a trabajar con Astra Control Service, configure su proveedor de cloud y inscríbase para obtener una cuenta Astra.
+
** Para los clústeres GKE, el servicio Astra Control utiliza https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service de NetApp para Google Cloud"^] O discos persistentes de Google como back-end de almacenamiento para sus volúmenes persistentes.
** Para clústeres AKS, el servicio de control Astra utiliza https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^] O almacenamiento en disco de Azure como back-end de almacenamiento para sus volúmenes persistentes.
** Para clústeres de Amazon EKS, utiliza Astra Control Service https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store"^] o. https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX para ONTAP de NetApp"^] como back-end de almacenamiento para sus volúmenes persistentes.


* Agregue su primera tecnología Kubernetes al servicio Astra Control. A continuación, el servicio de control de Astra realiza lo siguiente:
+
** Crea un almacén de objetos en su cuenta de proveedor de cloud, que es donde se almacenan las copias de backup.
+
En Azure, Astra Control Service también crea un grupo de recursos, una cuenta de almacenamiento y claves para el contenedor Blob.

** Crea un nuevo rol de administrador y una cuenta de servicio de Kubernetes en el clúster.
** Utiliza la nueva función de administración para instalar https://docs.netapp.com/us-en/trident/index.html["Astra Trident"^] en el clúster y para crear una o varias clases de almacenamiento.
** Si utiliza Azure NetApp Files o Cloud Volumes Service de NetApp para Google Cloud como back-end de almacenamiento, el servicio Astra Control utiliza Astra Trident para aprovisionar volúmenes persistentes para sus aplicaciones.


* En este momento, puede añadir aplicaciones al clúster. Se aprovisionan volúmenes persistentes en la nueva clase de almacenamiento predeterminada.
* A continuación, utilice Astra Control Service para gestionar estas aplicaciones y empiece a crear copias Snapshot, copias de seguridad y clones.


El plan gratuito de Astra Control le permite gestionar hasta 10 aplicaciones en su cuenta. Si desea gestionar más de 10 aplicaciones, tendrá que configurar la facturación mediante la actualización del plan gratuito al plan Premium.



== Cómo funciona Astra Control Center

Astra Control Center se ejecuta en forma local en su propia nube privada.

Astra Control Center es compatible con clústeres de Kubernetes con:

* Back-ends de almacenamiento de Trident con ONTAP 9.5 y versiones posteriores
* Astra Data Store back-ends


En un entorno conectado a la nube, Astra Control Center utiliza Cloud Insights para proporcionar supervisión y telemetría avanzadas. Ante la ausencia de una conexión con Cloud Insights, la telemetría y la supervisión limitadas (7 días de métricas) están disponibles en Astra Control Center y también se exportan a herramientas de supervisión nativas de Kubernetes (como Prometheus y Grafana) mediante puntos finales de métricas abiertas.

Astra Control Center está totalmente integrado en el ecosistema de AutoSupport y Active IQ para proporcionar a los usuarios y el soporte de NetApp información sobre solución de problemas y uso.

Puede probar Astra Control Center con una licencia de evaluación de 90 días. La versión de evaluación se admite a través de opciones de correo electrónico y comunidad (canal Slack). Además, tendrá acceso a los artículos de la base de conocimientos y a la documentación desde la consola de soporte del producto.

Para instalar y utilizar Astra Control Center, tendrá que estar seguro https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html["requisitos"].

En un nivel superior, Astra Control Center funciona de esta manera:

* Instala Astra Control Center en su entorno local. Obtenga más información sobre cómo https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html["Instalar Astra Control Center"].
* Puede realizar algunas tareas de configuración como las siguientes:
+
** Configurar la licencia.
** Añada el primer clúster.
** Añada el back-end de almacenamiento que se detecta al añadir el clúster.
** Agregue un bloque de almacenamiento de objetos que almacenará las copias de seguridad de la aplicación.




Obtenga más información sobre cómo https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html["Configure Astra Control Center"].

El Centro de Control de Astra hace lo siguiente:

* Detecta detalles del clúster, incluidos los espacios de nombres, y permite definir y proteger las aplicaciones.
* Descubre la configuración de Astra Trident o Astra Data Store en los clústeres que desea gestionar y le permite supervisar los back-ends de almacenamiento.


Puede añadir aplicaciones al clúster. O bien, si ya tiene algunas aplicaciones en el clúster que se están gestionando, puede utilizar Astra Control Center para gestionarlas. A continuación, utilice Astra Control Center para crear copias Snapshot, backups, clones y relaciones de replicación.



== Si quiere más información

* https://docs.netapp.com/us-en/astra/index.html["Documentación de Astra Control Service"^]
* https://docs.netapp.com/us-en/astra-control-center/index.html["Documentación de Astra Control Center"^]
* https://docs.netapp.com/us-en/astra-data-store/index.html["Documentación de Astra Data Store"]
* https://docs.netapp.com/us-en/trident/index.html["Documentación de Astra Trident"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["Utilice la API Astra Control"^]
* https://docs.netapp.com/us-en/cloudinsights/["Documentación de Cloud Insights"^]
* https://docs.netapp.com/us-en/ontap/index.html["Documentación de ONTAP"^]

