---
sidebar: sidebar 
permalink: use/unmanage.html 
keywords: unmanage app, remove app, stop managing app, stop managing clusters, unmanage cluster, remove cluster, kubernetes, astra, astra control 
summary: Elimine las aplicaciones o equipos que ya no desee gestionar desde Astra Control. 
---
= Desgestione aplicaciones y clústeres
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Elimine las aplicaciones o clústeres que ya no desee gestionar desde Astra Control Center.



== Desgestionar una aplicación

Detenga la gestión de las aplicaciones de las que ya no desee realizar copias de seguridad, copias Snapshot o clones de Astra Control Center.

* Se eliminarán todos los backups y las snapshots existentes.
* Las aplicaciones y los datos siguen estando disponibles.


.Pasos
. En la barra de navegación izquierda, seleccione *aplicaciones*.
. Seleccione la casilla de verificación de las aplicaciones que ya no desea administrar.
. En el menú *Acción*, seleccione *Unmanage*.
. Escriba "desgestionar" para confirmar.
. Confirme que desea anular la administración de las aplicaciones y, a continuación, seleccione *Sí, anular la administración de la aplicación*.


.Resultado
Astra Control Center deja de gestionar la aplicación.



== Desgestione un clúster

Anule la gestión del clúster que ya no desea administrar desde Astra Control Center.

* Con esta acción, Astra Control Center no gestiona su clúster. No realiza cambios en la configuración del clúster y no elimina el clúster.
* Trident no se desinstalará del clúster. https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html["Descubra cómo desinstalar Trident"^].



NOTE: Antes de anular la administración del clúster, debe anular la administración de las aplicaciones asociadas al clúster.

.Pasos
. En la barra de navegación izquierda, seleccione *Clusters*.
. Seleccione la casilla de comprobación del clúster que ya no desea gestionar en Astra Control Center.
. En el menú Opciones de la columna *acciones*, seleccione *Unmanage*.
. Confirme que desea anular la administración del clúster y, a continuación, seleccione *Sí, anular la administración del clúster*.


.Resultado
El estado del clúster cambia a *Extracción* y después de que el clúster se eliminará de la página *Clusters* y Astra Control Center ya no lo gestiona.


IMPORTANT: *Si el Centro de control de Astra y Cloud Insights no están conectados*, al anular la gestión del clúster se quitan todos los recursos que se instalaron para enviar datos de telemetría. *Si el Centro de control de Astra y Cloud Insights están conectados*, al anular la gestión del clúster sólo se elimina el `fluentbit` y.. `event-exporter` pods.
